# ADK Agent Definitions
adk_agents:  comic_story_creator_v1: # リストの要素ではなく、キーとしてエージェント名を指定
    model: "gemini-1.5-flash" # Agentのデフォルトモデル。ツール側でも指定可能
    description: "指定されたジャンルに基づいて漫画の基本的な物語構造（タイトル、プロットなど）を生成します。"
    instruction: |
      あなたはクリエイティブなストーリージェネレーターです。
      ユーザーから物語のジャンルを指定されたら、'generate_story_for_comic' ツールを使用して、
      そのジャンルに合った面白い物語の構造（タイトル、キャラクターの概要、プロットの起承転結、テーマ）を考案してください。
      ツールは物語構造をJSON形式で返します。そのJSONをそのままユーザーへの最終応答としてください。
      ユーザー入力は物語のジャンルです。
    tools:
      - "agents.story_tools.generate_story_for_comic" # 作成したツールのPythonパス
    model_name: "gemini-1.5-flash" # run_agent.py で読み込むために追加
    temperature: 0.7 # run_agent.py で読み込むために追加
    max_tokens: 1000 # run_agent.py で読み込むために追加

default_agent_id: "simple_story_agent_v1"

agents:
  - id: "simple_story_agent_v1"
    class: "agents.story_agent.SimpleStoryAgent"
    config:
      use_adk: false
      use_llm: true
      story_templates:
        default:
          setup: "平和な世界で暮らしていた主人公は、ある日突然、不思議な出来事に巻き込まれます。"
          conflict: "{genre}の要素を活かしながら、仲間たちと共に冒険を繰り広げ、ライバルとの対立や困難な課題に直面します。"
          resolution: "知恵と勇気で困難を乗り越え、真の目的を達成します。"
        adventure:
          setup: "冒険心あふれる主人公は、新たな大陸への旅路に出発します。"
          conflict: "{genre}の世界で、未知の敵と戦いながら、伝説の宝を探し求めます。"
          resolution: "多くの仲間と出会い、最後は皆で力を合わせて目標を達成します。"

  # character_agent_v1 と plot_optimizer_agent_v1 を agents リストに移動
  - id: "character_agent_v1"
    class: "agents.character_agent.CharacterAgent" # 仮のクラスパス、実際のクラス名に修正してください
    description: "Manages characters for the story."
    # 必要に応じてキャラクター管理用の設定を追加
    config: {} # 空のconfigでも良いので追加

  - id: "plot_optimizer_agent_v1"
    class: "agents.plot_optimizer_agent.PlotOptimizerAgent" # 仮のクラスパス、実際のクラス名に修正してください
    description: "Analyzes and suggests improvements for story plots using an LLM."
    llm_tool_id: "llm_tool_gemini_pro" # このIDのツールを参照
    model_name: "gemini-2.0-flash"
    prompt_template: |
      あなたはプロの脚本家であり、プロット分析の専門家です。
      以下のプロットの概要を分析し、より面白くするための具体的な改善案を3つ提案してください。
      改善案は、物語の緊張感を高める、キャラクターの動機を明確にする、あるいは読者の共感を呼ぶような視点からお願いします。

      プロット概要:
      {plot_summary}

      改善案:
      1. [改善案1]
      2. [改善案2]
      3. [改善案3]
    config: {} # 空のconfigでも良いので追加


tools:
  - id: "llm_tool_gemini_pro"
    class: "google.adk.tools.LLMTool" # ADK提供のLLMツールクラスを想定
    config:
      model_name: "gemini-2.0-flash"
      temperature: 0.7
      max_tokens: 1000
      prompt_templates:
        story:
          system: |
            あなたは創造的なストーリーテラーです。ユーザーのリクエストに基づいて、物語のタイトルとプロット（導入、葛藤、解決の3要素を含む）をJSON形式で提供してください。
            JSONのキーは "title" (文字列)、および "plot" (オブジェクトで、キーは "setup", "conflict", "resolution") としてください。
          user: |-
            ジャンル：{genre}

            上記のジャンルに基づいた物語を生成してください。